###########################
##### Data providers ######
###########################

data-providers:
  - name: pvpstats-kills
    type: PAPI # Data provider source type
    placeholder: "%pvpstats_kills%"

    update-period: 10s # 10m

    # Standard java string format. the number indicates how many decimal places to use.
    # i.e 0 for kills, you would want "$%.2f" for money etc.
    score-format: "%.0f"

    update-triggers:
      - trigger-type: PLAYER_JOIN
        delay: 5s

      - trigger-type: PLAYER_KILL
        delay: 5s


##########################
#### Data Visualizers ####
##########################

visualizers:
#  - type: HOLOGRAM
#


  - type: PLAYER

    title:
      enabled: true
      location: world 13.5 172 0.5 0 0


    providers:
      - name: pvpstats-kills
        show-since: 1m
        title: |-
          &0==============
          &aMinutely Kills
          &0==============
        npc-title: |-
          &e%rank%&a. &7%name%
          &e%value% &aKills

      - name: pvpstats-kills
        show-since: 1d
        title: |-
          &0===========
          &aDaily Kills
          &0===========
        npc-title: |-
          &e%rank%&a. &7%name%
          &e%value% &aKills

      - name: pvpstats-kills
        show-since: 100w
        title: |-
          &0==============
          &aAll time kills
          &0==============
        npc-title: |-
          &e%rank%&a. &7%name%
          &e%value% &aKills

    rotate-period: 2s

    watch-player: true
    watch-distance: 10

    npcs:
      - location: world 15.5 171 .5 90 0 # world x y z yaw pitch
        rank: 1
      - location: world 13.5 170 3.5 90 0
        rank: 2
      - location: world 13.5 169 -2.5 90 0
        rank: 3
